import "./globals.css";
import "flag-icons/css/flag-icons.min.css";
import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import { cn } from "@/lib/utils";
import QueryProvider from "@/providers/query-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import NextIntelProvider from "@/providers/next-intel-provider";
import { Toaster } from "sonner";
import { DirectionProvider } from "@/components/ui/direction";
import NavbarMenu from "@/components/navbar-menu/NavbarMenu";
import SiteExperience from "@/components/site-experience/SiteExperience";
import { Analytics } from "@vercel/analytics/next";

const vazirmatn = Vazirmatn({
  subsets: ["arabic"],
  variable: "--font-vazir",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const resolvedParams = await params;
  const locale = resolvedParams.locale;

  return (
    <html
      className={cn(
        "h-full",
        "antialiased",
        vazirmatn.variable,
        locale === "fa" ? "font-vazir" : "font-sans",
      )}
      dir={locale === "fa" ? "rtl" : "ltr"}
      suppressHydrationWarning
    >
      <body className="flex flex-col min-h-full">
        <DirectionProvider
          dir={locale === "fa" ? "rtl" : "ltr"}
          direction={locale === "fa" ? "rtl" : "ltr"}
        >
          <QueryProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <NextIntelProvider locale={locale}>
                <SiteExperience>
                  <NavbarMenu />
                  <main className="mt-12 lg:mt-26 mb-4">{children}</main>
                  <Toaster />
                </SiteExperience>
              </NextIntelProvider>
            </ThemeProvider>
          </QueryProvider>
        </DirectionProvider>
        <Analytics />
      </body>
    </html>
  );
}
